name: IOS - APP to IPA tests
on:
 push:
    branches: [ Kumaresan ]
 pull_request:
    types:
      - opened
    branches:    
      - 'releases/**' 
      
jobs:
  run_tests:
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v2
    - name: Read test.txt
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: ./A/B/C/D/1233333/**/test.txt
    - name: Echo text.txt
      run: echo "${{ steps.package.outputs.content }}"
