name: IOS - APP to IPA tests
on:
 push:
    branches: [ Kumaresan ]
 pull_request:
    types:
      - opened
    branches:    
      - 'releases/**' 
      
jobs:
  run_tests:
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v2
    - name: Echo text.txt
      run: | 
          echo "start file search"
          find ./A/B/C/D -name *.txt
          find ./Users/runner/Library/Developer/Xcode/DerivedData -name *.txt
          echo "end file search"
