name: IOS - APP to IPA tests
on:
 push:
    branches: [ Kumaresan ]
 pull_request:
    types:
      - opened
    branches:    
      - 'releases/**' 
      
jobs:
  run_tests:
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: Pods
        key: $('/Users/runner/work/mobile-app-account-holders/mobile-app-account-holders/ios/Podfile.lock')
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: |
        echo "default dire"
        ls
        echo "default dire1"
        mkdir -p ios/iphoneos/Payload
        mv /Users/runner/work/appToIpa/appToIpa/Alluo.app ios/iphoneos/Payload
        ls -R
        echo "before zip"
        cd ios/iphoneos
        zip -r Alluo.ipa Payload
        rm -rf Payload
        echo "list of dir"
        ls -R
