name: "exampleReport"
on: [push]
env:
  hardcoded_aws_response: "run": {

        "arn": "arn:aws:devicefarm:us-west-2:613203822881:run:9bf35c1e-ee79-42f2-b7d3-74a976d95dcb/98616d95-b866-4860-ad9d-77e22c4dc8b3",

        "name": "first_cli_run",

        "type": "APPIUM_JAVA_TESTNG",

        "platform": "ANDROID_APP",

        "created": "2022-03-21T06:09:59.028000+05:30",

        "status": "COMPLETED",

        "result": "PASSED",

        "started": "2022-03-21T06:09:59.028000+05:30",

        "stopped": "2022-03-21T06:14:38.493000+05:30",

        "counters": {

            "total": 3,

            "passed": 3,

            "failed": 0,

            "warned": 0,

            "errored": 0,

            "stopped": 0,

            "skipped": 0

        },

        "totalJobs": 1,

        "completedJobs": 1,

        "billingMethod": "METERED",

        "deviceMinutes": {

            "total": 3.15,

            "metered": 2.0,

            "unmetered": 0.0

        },

        "parsingResultUrl": "https://prod-us-west-2-results.s3-us-west-2.amazonaws.com/613203822881/9bf35c1e-ee79-42f2-b7d3-74a976d95dcb/98616d95-b866-4860-ad9d-77e22c4dc8b3/parsingResult.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220422T053245Z&X-Amz-SignedHeaders=host&X-Amz-Expires=259200&X-Amz-Credential=AKIAUJHLTYS5AWNTRO6L%2F20220422%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=2ca2b4fa237f8955b8c7833fbcd2aa8a3c49cf290fc917604b68eb911ecc204b",

        "appUpload": "arn:aws:devicefarm:us-west-2:613203822881:upload:9bf35c1e-ee79-42f2-b7d3-74a976d95dcb/32c794cd-3b54-4a92-a0f8-41b1794cdc69",

        "jobTimeoutMinutes": 150,

        "devicePoolArn": "arn:aws:devicefarm:us-west-2:613203822881:devicepool:9bf35c1e-ee79-42f2-b7d3-74a976d95dcb/9c8ee38d-bd4f-4fb4-a72e-38ad93c890a1",

        "radios": {

            "wifi": true,

            "bluetooth": false,

            "nfc": true,

            "gps": true

        }

    }

}"
jobs:
  # make sure the action works on a clean machines without building
  test_aws_response:
     runs-on: ubuntu-latest
     steps:
      - name: Publish Report
        run :
           echo $hardcoded_aws_response
