name: IOS - APP to IPA tests
on:
 push:
    branches: [ Kumaresan ]
 pull_request:
    types:
      - opened
    branches:    
      - 'releases/**' 
      
jobs:
  run_tests:
    runs-on: macos-11
    strategy:
      matrix:
        include:
          - xcode: "13.2"
            ios: "15.2"
    name: test iOS (${{ matrix.ios }})
    steps:
    - uses: actions/checkout@v2
    - name: Echo text.txt
      run: | 
          echo "start file search"
          echo ${{ github.workspace }}
          #find ./A/B/C/D -name *.txt
          
          #find ${{ github.workspace }} -name *.txt
          #find /Users/runner/work/testbranch/testbranch/Users/runner/Library/Developer/Xcode/DerivedData/Alluo-gxbtvocshxocwqeunjvfradwcsvv/Build/Products/Debug-iphonesimulator -name *.txt
          echo "end file search"
          
          #find . -name xcode.txt
          #find . -name alluo.txt
          
          find ./Users/runner/Library/Developer/Xcode/DerivedData -name alluo.txt
          find ./runner/Library/Developer/Xcode/DerivedData -name alluo.txt
          echo "heee"

